# Guided Exploration No. 3
# ADRIAN COMBELIC

# This imports and gives us access to the random library
import random
# This is an empty list where we will store all possible names from the rap-names.txt file
possible_names = []
# This will store the names generated by our code
outputFile = open('rap-names-output.txt', 'w')
# This will open the rap-names.txt file for read access and I believe stores it in a new variable called dataFile
with open('rap-names.txt', 'r') as dataFile:
    # the for loop will iterate through each line in the rap-names text file
    for name in dataFile:
        # through each iteration a name will be added to our empty list with the invisible linefeed stripped off
        possible_names.append(name.rstrip())
# This will ask the user to input how many rap names they would like to create, assigning the number to the variable 'count'
count = int(input('How many rap names would you like to create? '))
# This will ask the user how many parts the name should contain
parts = int(input('How many parts should the name contain? '))

# This for loop will iterate equal to how many names the user wanted to generate
for i in range(count):
    # The parts of the name will be held in this empty list
    name_parts = []
    # This nested loop will iterate equal to the number inputed to the parts variable
    for j in range(parts):
        # for each iteration a randomly selected number of a name from the possible names list will be appended to the empty name_parts list
        name_parts.append(possible_names[random.randint(0, len(possible_names)-1)])
    # This code will join join the randomly selected name parts by writing them to the outputFile
    outputFile.write(f"{' '.join(name_parts)}\n")
    # This code will print it out to the terminal
    print(f"{' '.join(name_parts)}")
# This will close the file
outputFile.close()
